/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qppinrottawxfdblhgab"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwcGlucm90dGF3eGZkYmxoZ2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI0MTc3NjEsImV4cCI6MjA5Nzk5Mzc2MX0.3iuezE-t7-LOBFUlhpD8PqBtzqnvJ-2VKcKPu5ni6SE"